Repository UMC-5th-Coumo/Coumo_Web, pull requests merged in 2024-02, with the labels that each got.

#86 [Feat/#78]: 고객 데이터 필터링, 검색 기능
  src/components/admin/customer/customerManage/CustomerDetail.jsx
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/pages/customer/CustomerManage.jsx
  src/redux/slices/customerSlice.js
Labels: feat

#89 [Feat/#85] 아이디 창, 비밀번호 재설정
  src/App.js
  src/assets/icon/Profile.svg
  src/assets/index.js
  src/components/find/FindForm.jsx
  src/pages/find/FindId.jsx
  src/pages/find/FindPw.jsx
  src/pages/find/FoundId.jsx
  src/pages/find/RePw.jsx
Labels: feat

#92 [Style/#91]: 고객 데이터 관리 반응형 구현
  src/App.js
  src/assets/data/chartOptions.js
  src/assets/data/tabData.js
  src/components/admin/customer/common/charts/AgeGroupChart.jsx
  src/components/admin/customer/common/charts/BarChart.jsx
  src/components/admin/customer/common/charts/DoughnutChart.jsx
  src/components/admin/customer/common/charts/LineChart.jsx
  src/components/admin/customer/common/tabMenu/TabMenuBar.jsx
  src/components/admin/customer/customerManage/CustomerDetail.jsx
  src/components/admin/customer/customerManage/CustomerGroupButton.jsx
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/components/admin/customer/visitAnalysis/Calendar.jsx
  src/components/admin/customer/visitAnalysis/VisitCount.jsx
  src/components/admin/customer/visitAnalysis/groupTab/GroupTab.jsx
  src/components/admin/customer/visitAnalysis/tabMenu/TabMenu.jsx
  src/components/admin/customer/visitAnalysis/tabMenu/TabMenuBar.jsx
  src/components/common/AdminVerticalHeader.jsx
  src/components/common/Button.jsx
  src/components/common/RadioBtn.jsx
  src/pages/Customer.jsx
  src/pages/customer/CustomerManage.jsx
  src/pages/customer/VisitAnalysis.jsx
  src/pages/customer/visitAnalysis/DailyVisit.jsx
  src/pages/customer/visitAnalysis/DemographicVisit.jsx
  src/pages/customer/visitAnalysis/TimeVisit.jsx
Labels: style

#95 [Feat/#90] 내가 쓴 글 리스트 수정
  src/components/admin/coupon/Category.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/TagButton.jsx
  src/components/common/Header.jsx
  src/components/common/RadioBtn.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/redux/reducer.js
  src/redux/slices/postSlice.js
Labels: feat

#97 [Feat/#96] 글쓰기 이미지, 텍스트 분리
  src/App.js
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/writePost/Edit.jsx
  src/components/common/AdminHeader.jsx
  src/components/common/Input.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/WritePost.jsx
Labels: feat

#98 [Feat/#93]: 영업시간 설정 기능
  src/assets/data/workingHourData.js
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/pages/shop/BasicInfo.jsx
Labels: feat

#99 [Style/#94]: 매장 기본정보 페이지 반응형 구현
  src/components/admin/coupon/Category.jsx
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/components/admin/writePost/Edit.jsx
  src/components/common/Input.jsx
  src/components/common/Title.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/shop/BasicInfo.jsx
Labels: style

#101 [API/#100]: 서버 연동 (회원가입)
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/BasicInfo.jsx
  src/redux/reducer.js
  src/redux/slices/postSlice.js
  src/redux/thunks/getCustomers.js
Labels: API

#106 [Style/#105]: ThemeProvider 적용
  src/components/admin/coupon/Category.jsx
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/coupon/CouponStep.jsx
  src/components/admin/coupon/RadioButton.jsx
  src/components/admin/coupon/ReasonCard.jsx
  src/components/admin/coupon/Stamp.jsx
  src/components/admin/customer/customerManage/CustomerDetail.jsx
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/components/admin/customer/monthlyReport/MonthPicker.jsx
  src/components/admin/customer/visitAnalysis/Calendar.jsx
  src/components/admin/customer/visitAnalysis/VisitCount.jsx
  src/components/admin/customer/visitAnalysis/groupTab/GroupTab.jsx
  src/components/admin/customer/visitAnalysis/index/Index.jsx
  src/components/admin/customer/visitAnalysis/index/IndexBar.jsx
  src/components/admin/customer/visitAnalysis/tabMenu/TabMenu.jsx
  src/components/admin/neighborhood/ConfirmModal.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/TagButton.jsx
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/MenuMore.jsx
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/components/admin/writePost/Edit.jsx
  src/components/common/AdminHeader.jsx
  src/components/common/AdminVerticalHeader.jsx
  src/components/common/Button.jsx
  src/components/common/FormPopUp.jsx
  src/components/common/Header.jsx
  src/components/common/Input.jsx
  src/components/common/InputJoin.jsx
  src/components/common/RadioBtn.jsx
  src/components/common/Tab.jsx
  src/components/common/Title.jsx
  src/components/find/FindForm.jsx
  src/components/home/Banner.jsx
  src/components/home/Plan.jsx
  src/components/home/PricePlan.jsx
  src/components/home/ServiceIntro.jsx
  src/components/home/TitleChip.jsx
  src/components/login/LoginBox.jsx
  src/index.js
  src/pages/MyPage.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/coupon/UIServiceAd.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/customer/CustomerManage.jsx
  src/pages/find/FoundId.jsx
  src/pages/find/RePw.jsx
  src/pages/join/Congratulate.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/BasicInfo.jsx
  src/pages/shop/StoreInfo.jsx
  src/styles/theme.js
Labels: style

#110 [API/#107]: 매장관리 > 기본정보 서버 연동 준비
  src/assets/data/workingHourData.js
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/pages/shop/BasicInfo.jsx
Labels: API

#111 [api/#108]: 쿠폰 관리 서버 연동 준비
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/coupon/UIServiceForm.jsx
Labels: API

#114 [Feat/#112]: 팝업 컴포넌트 구현
  src/components/admin/neighborhood/Edit.jsx
  src/components/common/RadioBtn.jsx
  src/components/common/popUp/OneBtnPopUp.jsx
  src/components/common/popUp/TwoBtnPopUp.jsx
  src/pages/MyPage.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/customer/CustomerManage.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/redux/slices/postSlice.js
  src/styles/GlobalStyle.js
Labels: feat

#116 [Style/#115]: 기본정보 페이지 반응형
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/components/common/Input.jsx
  src/components/common/RadioBtn.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/shop/BasicInfo.jsx
Labels: style

#118 [Feat/#102]: 매장 설명, 동네 소식 페이지 반응형 구현
  src/components/admin/coupon/Category.jsx
  src/components/admin/neighborhood/Edit.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/shop/ImageBlock.jsx
  src/components/common/Input.jsx
  src/components/common/RadioBtn.jsx
  src/pages/neighborhood/MyPosts.jsx
Labels: feat

#121 [Feat/#102]: 페이지별 padding 수정
  src/components/admin/neighborhood/Post.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/StoreInfo.jsx
Labels: feat

#122 [Style/#120]: 마이페이지 반응형 구현
  src/components/admin/myPage/ListBox.jsx
  src/pages/MyPage.jsx
  src/pages/myPage/UIServiceDetail.jsx
  src/pages/myPage/UIServiceList.jsx
Labels: style

#124 [Style/#123]: 쿠폰관리 페이지 반응형
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/coupon/RadioButton.jsx
  src/components/admin/coupon/Stamp.jsx
  src/components/common/RadioBtn.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/coupon/UIServiceForm.jsx
Labels: style

#126 [Style/#125]: 팝업 반응형 구현
  src/components/common/AdminVerticalHeader.jsx
  src/components/common/popUp/OneBtnPopUp.jsx
  src/components/common/popUp/TwoBtnPopUp.jsx
  src/pages/MyPage.jsx
Labels: style

#129 [API/#128] 동네소식 서버 연동 준비
  src/components/admin/neighborhood/Edit.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/shop/ImageBlock.jsx
  src/components/common/AdminHeader.jsx
  src/components/common/AdminVerticalHeader.jsx
  src/components/common/RadioBtn.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/StoreInfo.jsx
  src/redux/slices/postSlice.js
  src/redux/thunks/deleteMyPost.js
  src/redux/thunks/getMyEdit.js
  src/redux/thunks/getMyPostView.js
  src/redux/thunks/getMyPosts.js
  src/redux/thunks/patchMyEdit.js
Labels: API

#127 [Redux/#84]: 게시글 redux 연동
  src/components/admin/neighborhood/Edit.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/shop/ImageBlock.jsx
  src/components/common/AdminHeader.jsx
  src/components/common/AdminVerticalHeader.jsx
  src/components/common/RadioBtn.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/StoreInfo.jsx
  src/redux/slices/postSlice.js
Labels: redux

#134 [Style/#132]: 회원가입/로그인 사이즈 조절
  src/App.js
  src/assets/icon/CheckBoxDefault.svg
  src/assets/icon/CheckBoxSelected.svg
  src/assets/icon/LogoCongratulate.svg
  src/assets/icon/Profile.svg
  src/components/common/InputJoin.jsx
  src/components/find/FindForm.jsx
  src/components/login/LoginBox.jsx
  src/pages/MyPage.jsx
  src/pages/find/FoundId.jsx
  src/pages/find/RePw.jsx
  src/pages/join/Congratulate.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
Labels: style

#138 [Style/#131]: Color 정의 수정
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/coupon/CouponStep.jsx
  src/components/admin/coupon/RadioButton.jsx
  src/components/admin/coupon/ReasonCard.jsx
  src/components/admin/coupon/Stamp.jsx
  src/components/admin/customer/customerManage/CustomerDetail.jsx
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/components/admin/customer/monthlyReport/MonthPicker.jsx
  src/components/admin/customer/visitAnalysis/Calendar.jsx
  src/components/admin/customer/visitAnalysis/VisitCount.jsx
  src/components/admin/customer/visitAnalysis/groupTab/GroupTab.jsx
  src/components/admin/customer/visitAnalysis/index/Index.jsx
  src/components/admin/customer/visitAnalysis/index/IndexBar.jsx
  src/components/admin/customer/visitAnalysis/tabMenu/TabMenu.jsx
  src/components/admin/myPage/ListBox.jsx
  src/components/admin/neighborhood/Edit.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/TagButton.jsx
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/MenuMore.jsx
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/components/common/Button.jsx
  src/components/common/Input.jsx
  src/components/common/InputJoin.jsx
  src/components/common/RadioBtn.jsx
  src/components/common/Tab.jsx
  src/components/find/FindForm.jsx
  src/components/login/LoginBox.jsx
  src/pages/Coupon.jsx
  src/pages/Home.jsx
  src/pages/MyPage.jsx
  src/pages/Neighborhood.jsx
  src/pages/coupon/UIServiceAd.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/find/RePw.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
  src/pages/myPage/UIServiceDetail.jsx
  src/pages/myPage/UIServiceList.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/shop/BasicInfo.jsx
  src/pages/shop/StoreInfo.jsx
  src/styles/theme.js
Labels: style

#141 [Feat/#140]: 매장관리> 메뉴 등록 삭제 버튼, 신메뉴 체크 박스
  src/assets/icon/Cancel.svg
  src/assets/index.js
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/MenuMore.jsx
  src/components/common/Input.jsx
  src/pages/shop/StoreInfo.jsx
Labels: feat, style

#144 [Style/#135]: 고객 데이터 관리 배치 변경
  src/assets/icon/Profile.svg
  src/components/admin/customer/customerManage/CustomerDetail.jsx
  src/components/admin/customer/customerManage/CustomerGroupButton.jsx
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/components/admin/customer/customerManage/CustomerRadio.jsx
  src/pages/Customer.jsx
  src/pages/customer/CustomerManage.jsx
  src/pages/customer/MonthlyReport.jsx
  src/pages/customer/VisitAnalysis.jsx
Labels: style

#145 [Refactor/#133]: 회원가입/로그인 코드 refactoring
  src/components/find/FindForm.jsx
  src/components/join/CheckButton.jsx
  src/components/join/CheckList.jsx
  src/components/join/ErrorMsg.jsx
  src/components/join/JoinBtn.jsx
  src/components/login/LoginBox.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
Labels: refactor

#146 [Feat/#142]: 이미지 컴포넌트 삭제
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/MenuMore.jsx
  src/pages/shop/StoreInfo.jsx
Labels: feat

#149 [Style/#143]: 쿠폰 UI 서비스 반응형
  src/App.js
  src/components/admin/coupon/CouponStep.jsx
  src/components/admin/coupon/ReasonCard.jsx
  src/components/common/AdminHeader.jsx
  src/pages/Coupon.jsx
  src/pages/coupon/UIServiceAd.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/customer/CustomerManage.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/styles/GlobalStyle.js
Labels: style

#153 [Fix/#152]: 팝업, 고객 데이터 배경색 수정
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/coupon/RadioButton.jsx
  src/components/admin/coupon/Stamp.jsx
  src/components/admin/customer/customerManage/CustomerDetail.jsx
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/components/admin/customer/customerManage/CustomerRadio.jsx
  src/components/common/popUp/OneBtnPopUp.jsx
  src/components/common/popUp/TwoBtnPopUp.jsx
  src/pages/customer/CustomerManage.jsx
Labels: fix

#156 [Style/#154]: 내가 쓴 글 테두리 처리
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/PostList.jsx
  src/components/admin/neighborhood/TagButton.jsx
  src/components/common/RadioBtn.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
Labels: fix, refactor, style

#158 [Style/#157]: vertical header 스타일링
  src/assets/data/headerData.js
  src/components/common/AdminVerticalHeader.jsx
  src/components/common/VerticalHeaderMenu.jsx
Labels: refactor, style

#160 [Redux/#159]: redux-persist 설정 변경
  src/redux/store.js
Labels: redux

#163 [Feat/#162]: 최초 로그인 후 팝업 구현
  package-lock.json
  package.json
  src/App.js
  src/assets/image/checkLottie.json
  src/assets/image/partyPopper.png
  src/components/admin/formPopUp/FormPopUp.jsx
  src/components/admin/formPopUp/MultiStep.jsx
  src/components/admin/formPopUp/Step1.jsx
  src/components/admin/formPopUp/Step2.jsx
  src/components/admin/formPopUp/Step3.jsx
  src/components/admin/formPopUp/Welcome.jsx
  src/components/common/AdminVerticalHeader.jsx
  src/pages/AdminHome.jsx
Labels: feat

#164 [Style/#161]: 이미지 등록 컴포넌트 수정
  package-lock.json
  package.json
  src/App.js
  src/components/admin/shop/ImageBlock.jsx
  src/components/login/LoginBox.jsx
  src/pages/Neighborhood.jsx
  src/pages/Shop.jsx
  src/pages/join/JoinTwoStep.jsx
  src/setupProxy.js
Labels: feat, style

#173 [Feat/#170]: 어드민 홈화면 구현
  src/assets/data/chartOptions.js
  src/components/admin/customer/common/charts/AgeGroupChart.jsx
  src/components/admin/customer/common/charts/LineChart.jsx
  src/components/admin/home/CouponInfo.jsx
  src/components/admin/home/CustomerInfo.jsx
  src/components/admin/home/DayGraphInfo.jsx
  src/components/admin/home/GenderGraphInfo.jsx
  src/components/admin/home/StoreInfo.jsx
  src/components/admin/home/WorkingHours.jsx
  src/components/common/AdminVerticalHeader.jsx
  src/pages/AdminHome.jsx
Labels: feat

#177 [API/#176] 서버 연동 테스트
  src/components/admin/formPopUp/FormPopUp.jsx
  src/components/admin/formPopUp/Step1.jsx
  src/components/admin/formPopUp/Step2.jsx
  src/pages/AdminHome.jsx
Labels: API

#178 [API/#176]: proxy 제거
  src/pages/join/JoinTwoStep.jsx
  src/setupProxy.js
Labels: API

#174 [Feat/#172]: 도장 5종 선택 기능
  src/assets/data/stampData.js
  src/assets/icon/stamp1.svg
  src/assets/icon/stamp2.svg
  src/assets/icon/stamp3.svg
  src/assets/icon/stamp4.svg
  src/assets/icon/stamp5.svg
  src/assets/index.js
  src/components/admin/coupon/Stamp.jsx
  src/components/admin/coupon/StampList.jsx
  src/pages/coupon/AddCoupon.jsx
Labels: feat

#179 [Fix]: design 회의 수정사항
  src/api/axios.js
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/components/admin/customer/visitAnalysis/tabMenu/TabMenu.jsx
  src/components/admin/home/CouponInfo.jsx
  src/components/admin/home/CustomerInfo.jsx
  src/components/admin/home/DayGraphInfo.jsx
  src/components/admin/home/GenderGraphInfo.jsx
  src/components/admin/home/StoreInfo.jsx
  src/components/admin/home/WorkingHours.jsx
  src/components/admin/myPage/ListBox.jsx
  src/components/admin/neighborhood/PostList.jsx
  src/components/admin/shop/ImageBlock.jsx
  src/components/common/AdminHeader.jsx
  src/components/common/AdminVerticalHeader.jsx
  src/components/common/VerticalHeaderMenu.jsx
  src/pages/AdminHome.jsx
  src/pages/MyPage.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/coupon/UIServiceAd.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/styles/theme.js
Labels: fix, style

#183 [Style/#182]: 쿠폰 관리 페이지 디자인 수정
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/neighborhood/Edit.jsx
  src/components/common/AdminHeader.jsx
  src/components/common/Input.jsx
  src/components/common/InputJoin.jsx
  src/components/login/LoginBox.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/shop/StoreInfo.jsx
Labels: style

#185 [Style/#184]: 고객 관리 페이지 디자인 수정
  src/assets/data/tabData.js
  src/assets/icon/gender.svg
  src/assets/icon/person.svg
  src/assets/index.js
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/components/admin/customer/visitAnalysis/Calendar.jsx
  src/components/admin/customer/visitAnalysis/tabMenu/TabMenu.jsx
  src/components/admin/customer/visitAnalysis/tabMenu/TabMenuBar.jsx
  src/components/admin/neighborhood/Edit.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/customer/CustomerManage.jsx
  src/pages/customer/VisitAnalysis.jsx
  src/pages/customer/visitAnalysis/DailyVisit.jsx
  src/pages/customer/visitAnalysis/DemographicVisit.jsx
  src/pages/customer/visitAnalysis/TimeVisit.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/shop/StoreInfo.jsx
Labels: style

#186 [Feat/#169]: 최초 로그인 팝업 내용
  src/components/admin/coupon/Category.jsx
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/coupon/RadioButton.jsx
  src/components/admin/coupon/Stamp.jsx
  src/components/admin/coupon/StampCount.jsx
  src/components/admin/coupon/StampList.jsx
  src/components/admin/formPopUp/FormPopUp.jsx
  src/components/admin/formPopUp/Step1.jsx
  src/components/admin/formPopUp/Step2.jsx
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/components/common/Input.jsx
  src/components/common/RadioBtn.jsx
  src/pages/join/JoinTwoStep.jsx
Labels: feat

#188 [Feat/#171]: 페이지 뒤로가기 기능
  src/App.js
  src/components/common/ScrollTop.jsx
  src/pages/myPage/UIServiceDetail.jsx
  src/pages/myPage/UIServiceList.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
Labels: feat

#190 [Style/#187]: 동네소식 및 회원가입 등 디자인 수정사항
  src/assets/data/categoryData.js
  src/assets/icon/PageNext.svg
  src/assets/icon/PageNextDisable.svg
  src/assets/icon/PagePrev.svg
  src/assets/icon/PagePrevDisable.svg
  src/assets/index.js
  src/components/admin/coupon/StampCount.jsx
  src/components/admin/coupon/StampList.jsx
  src/components/admin/formPopUp/Step1.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/PostList.jsx
  src/components/admin/shop/MenuMore.jsx
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/components/common/popUp/OneBtnPopUp.jsx
  src/pages/find/FoundId.jsx
  src/pages/find/RePw.jsx
  src/pages/join/JoinTwoStep.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/BasicInfo.jsx
Labels: style

#191 [Style/#189]: 대시보드, 마이페이지 디자인 수정
  src/components/admin/home/CustomerInfo.jsx
  src/pages/MyPage.jsx
  src/pages/myPage/UIServiceDetail.jsx
Labels: style

#192 [Style/#175]: 월간 레포트 디자인 변경
  src/components/admin/customer/monthlyReport/MonthPicker.jsx
  src/pages/customer/MonthlyReport.jsx
Labels: style

#194 [Feat/#193]: 404 page 구현
  src/App.js
  src/pages/NotFound.jsx
Labels: feat

#197 [Style/#195]: 매장관리 > 기본정보 배치 변경
  src/components/admin/formPopUp/Step1.jsx
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/pages/shop/BasicInfo.jsx
Labels: style

#201 [API/#151]: 로그인 서버 연동
  src/components/find/FindForm.jsx
  src/components/join/CheckButton.jsx
  src/components/login/LoginBox.jsx
  src/pages/MyPage.jsx
  src/pages/find/FindId.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
  src/redux/slices/userSlice.js
Labels: API

#198 [Style/#196]: 내가 쓴 글 보기 이미지 수정
  src/pages/join/JoinTwoStep.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/redux/slices/postSlice.js
  src/redux/slices/userSlice.js
Labels: style

#204 [Style/#202]: 매장 설명 페이지 디자인 수정
  src/assets/data/chartOptions.js
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/MenuMore.jsx
  src/pages/shop/StoreInfo.jsx
Labels: style

#206 [API/#205]: 마이페이지 서버 연동
  src/components/admin/myPage/Profile.jsx
  src/components/login/LoginBox.jsx
  src/pages/MyPage.jsx
  src/redux/slices/userSlice.js
Labels: API

#210 [Feat/#209]: input 데이터 검증
  package-lock.json
  package.json
  src/assets/data/headerData.js
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/MenuItem.jsx
  src/components/admin/shop/MenuMore.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/shop/BasicInfo.jsx
  src/pages/shop/StoreInfo.jsx
Labels: feat, refactor

#211 [API/#207]: 매장관리 > 기본 정보 서버 연동
  src/api/axios.js
  src/assets/data/workingHourData.js
  src/components/admin/shop/AddressInput.jsx
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/components/login/LoginBox.jsx
  src/pages/MyPage.jsx
  src/pages/shop/BasicInfo.jsx
  src/redux/reducer.js
  src/redux/slices/storeSlice.js
Labels: API

#214 [Feat/#200]: textarea 글자 제한
  src/components/admin/neighborhood/Edit.jsx
  src/pages/join/JoinTwoStep.jsx
  src/pages/shop/BasicInfo.jsx
  src/pages/shop/StoreInfo.jsx
Labels: feat

#220 [API/#208]: 매장 관리 > 매장설명 서버 연동
  src/api/axios.js
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/MenuItem.jsx
  src/pages/shop/StoreInfo.jsx
Labels: API

#222 [API/#221]: 방문분석 서버 연동
  src/assets/data/tabData.js
  src/components/admin/customer/common/charts/AgeGroupChart.jsx
  src/components/admin/customer/common/charts/BarChart.jsx
  src/components/admin/customer/common/charts/DoughnutChart.jsx
  src/components/admin/customer/common/charts/LineChart.jsx
  src/components/admin/customer/visitAnalysis/Calendar.jsx
  src/components/admin/customer/visitAnalysis/VisitCount.jsx
  src/pages/customer/visitAnalysis/DailyVisit.jsx
  src/pages/customer/visitAnalysis/DemographicVisit.jsx
  src/pages/customer/visitAnalysis/TimeVisit.jsx
Labels: API

#228 [Fix/#226]: 고객 관리 서버 연동 오류 수정
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/components/admin/customer/visitAnalysis/Calendar.jsx
  src/components/admin/home/DayGraphInfo.jsx
  src/components/admin/home/GenderGraphInfo.jsx
  src/pages/AdminHome.jsx
  src/pages/customer/visitAnalysis/DailyVisit.jsx
  src/pages/customer/visitAnalysis/DemographicVisit.jsx
  src/pages/customer/visitAnalysis/TimeVisit.jsx
Labels: fix

#230 [API/#229]: 월간레포트 서버 연동
  src/components/admin/customer/common/charts/BarChart.jsx
  src/components/admin/customer/monthlyReport/AgeStatic.jsx
  src/components/admin/customer/monthlyReport/CustomerCount.jsx
  src/components/admin/customer/monthlyReport/DayVisitStatic.jsx
  src/components/admin/customer/monthlyReport/MonthPicker.jsx
  src/pages/customer/MonthlyReport.jsx
Labels: API

#232 [Style/#231]: 로그인 배경 변경
  src/App.js
  src/assets/icon/LogoCongratulate.svg
  src/components/find/FindForm.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/pages/find/FindId.jsx
  src/pages/find/FindPw.jsx
  src/pages/find/FoundId.jsx
  src/pages/find/RePw.jsx
  src/pages/join/Congratulate.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
Labels: style

#234 [Fix/#233]: 매장설명 API 연동 오류 수정
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/StoreImage.jsx
  src/pages/shop/StoreInfo.jsx
Labels: fix

#239 [API/#227]: 홈화면 서버 연동
  src/assets/index.js
  src/components/admin/customer/common/charts/LineChart.jsx
  src/components/admin/customer/monthlyReport/CustomerCount.jsx
  src/components/admin/home/CouponInfo.jsx
  src/components/admin/home/CustomerInfo.jsx
  src/components/admin/home/DayGraphInfo.jsx
  src/components/admin/home/GenderGraphInfo.jsx
  src/components/admin/neighborhood/Edit.jsx
  src/pages/AdminHome.jsx
  src/pages/shop/BasicInfo.jsx
  src/pages/shop/StoreInfo.jsx
  src/redux/slices/storeSlice.js
  src/redux/thunks/getStoreInfo.js
  src/redux/thunks/modifyStoreInfo.js
Labels: API

#241 [Fix/#240]: 매장관리 > 기본정보 redux 연동 오류 수정
  src/assets/data/categoryData.js
  src/components/admin/home/StoreInfo.jsx
  src/components/admin/home/WorkingHours.jsx
  src/redux/slices/storeSlice.js
  src/redux/thunks/getStoreInfo 2.js
Labels: fix

#246 [Feat/#238]: 로그인 정보 저장 기능
  src/assets/data/categoryData.js
  src/components/admin/neighborhood/Edit.jsx
  src/components/login/LoginBox.jsx
  src/pages/AdminHome.jsx
  src/pages/join/Congratulate.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/StoreInfo.jsx
Labels: feat

#247 [API/#242]: 쿠폰 등록하기 서버 연동
  src/assets/data/stampData.js
  src/assets/icon/stamp2.svg
  src/assets/icon/stamp3.svg
  src/assets/icon/stamp4.svg
  src/assets/icon/stamp5.svg
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/coupon/StampCount.jsx
  src/components/admin/home/CouponInfo.jsx
  src/pages/AdminHome.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/customer/CustomerManage.jsx
  src/pages/customer/MonthlyReport.jsx
  src/pages/customer/visitAnalysis/DailyVisit.jsx
  src/pages/customer/visitAnalysis/DemographicVisit.jsx
  src/pages/customer/visitAnalysis/TimeVisit.jsx
  src/pages/shop/BasicInfo.jsx
Labels: API

#252 [Fix/#251]: 콘솔 오류 수정
  src/components/admin/coupon/Category.jsx
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/coupon/RadioButton.jsx
  src/components/admin/coupon/Stamp.jsx
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/components/admin/customer/customerManage/CustomerRadio.jsx
  src/components/admin/customer/monthlyReport/CustomerCount.jsx
  src/components/admin/customer/visitAnalysis/Calendar.jsx
  src/components/admin/customer/visitAnalysis/groupTab/GroupTab.jsx
  src/components/admin/customer/visitAnalysis/index/Index.jsx
  src/components/admin/customer/visitAnalysis/tabMenu/TabMenu.jsx
  src/components/admin/formPopUp/MultiStep.jsx
  src/components/admin/formPopUp/Step3.jsx
  src/components/admin/home/CouponInfo.jsx
  src/components/admin/home/CustomerInfo.jsx
  src/components/admin/myPage/Profile.jsx
  src/components/admin/neighborhood/ConfirmModal.jsx
  src/components/admin/neighborhood/Edit.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/PostList.jsx
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/MenuItem.jsx
  src/components/admin/shop/workingHour/Dropdown.jsx
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/components/common/AdminVerticalHeader.jsx
  src/components/common/Button.jsx
  src/components/common/Input.jsx
  src/components/common/InputJoin.jsx
  src/components/common/RadioBtn.jsx
  src/components/common/VerticalHeaderMenu.jsx
  src/components/common/popUp/OneBtnPopUp.jsx
  src/components/common/popUp/TwoBtnPopUp.jsx
  src/components/join/JoinBtn.jsx
  src/components/login/LoginBox.jsx
  src/pages/MyPage.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/coupon/UIServiceAd.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/customer/CustomerManage.jsx
  src/pages/find/FoundId.jsx
  src/pages/join/Congratulate.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/StoreInfo.jsx
Labels: fix

#254 [Fix/#253]: api 토큰 오류 수정
  src/api/axios.js
  src/components/admin/customer/monthlyReport/AgeStatic.jsx
  src/components/admin/customer/monthlyReport/DayVisitStatic.jsx
  src/components/admin/formPopUp/FormPopUp.jsx
  src/components/admin/formPopUp/Step4 2.jsx
  src/components/admin/home/DayGraphInfo.jsx
  src/components/admin/home/GenderGraphInfo.jsx
  src/components/admin/neighborhood/Edit.jsx
  src/components/find/FindForm.jsx
  src/pages/AdminHome.jsx
  src/pages/MyPage.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/customer/MonthlyReport.jsx
  src/pages/customer/visitAnalysis/DailyVisit.jsx
  src/pages/customer/visitAnalysis/DemographicVisit.jsx
  src/pages/customer/visitAnalysis/TimeVisit.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/shop/StoreInfo.jsx
  src/redux/thunks/getCustomers.js
  src/redux/thunks/getStoreInfo.js
  src/redux/thunks/modifyStoreInfo.js
Labels: fix

#255 [API/#224]: 동네소식 서버 연동
  src/api/axios.js
  src/assets/data/categoryData.js
  src/components/admin/formPopUp/FormPopUp.jsx
  src/components/admin/neighborhood/Edit.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/PostList.jsx
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/StoreImage.jsx
  src/components/common/AdminVerticalHeader.jsx
  src/components/login/LoginBox.jsx
  src/pages/AdminHome.jsx
  src/pages/MyPage.jsx
  src/pages/Neighborhood.jsx
  src/pages/find/RePw.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/StoreInfo.jsx
  src/redux/reducer.js
  src/redux/slices/postSlice.js
  src/redux/thunks/deleteMyPost.js
  src/redux/thunks/getMyEdit.js
  src/redux/thunks/getMyPostView.js
  src/redux/thunks/getMyPosts.js
  src/redux/thunks/patchMyEdit.js
Labels: API

#257 [API/#256]: 회원탈퇴, 비밀번호 찾기, 쿠폰 UI 서비스 신청서 서버연동
  src/App.js
  src/assets/data/categoryData.js
  src/components/admin/formPopUp/FormPopUp.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/find/FindForm.jsx
  src/pages/MyPage.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/find/FindId.jsx
  src/pages/find/FindPw.jsx
  src/pages/find/FoundId.jsx
  src/pages/find/RePw.jsx
  src/pages/join/Congratulate.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPosts.jsx
Labels: API

#263 [Fix/#259]: 휴무 null로 변경
  src/api/axios.js
  src/assets/data/categoryData.js
  src/components/admin/home/WorkingHours.jsx
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/pages/shop/BasicInfo.jsx
Labels: fix

#261 [Style/#260]: 홈화면 헤더, 배너 변경
  src/assets/icon/BigLogo.svg
  src/assets/icon/CouponIcon.svg
  src/assets/icon/Logo.svg
  src/assets/icon/Logo_Purple.svg
  src/assets/icon/Symbol.svg
  src/assets/index.js
  src/components/common/AdminHeader.jsx
  src/components/common/Header.jsx
  src/components/home/Banner.jsx
  src/styles/theme.js
Labels: style

#265 [Fix/#264]: 휴무 date type 변경
  src/api/axios.js
  src/components/admin/customer/monthlyReport/AgeStatic.jsx
  src/components/admin/customer/monthlyReport/DayVisitStatic.jsx
  src/components/admin/home/DayGraphInfo.jsx
  src/components/admin/home/GenderGraphInfo.jsx
  src/components/admin/home/WorkingHours.jsx
  src/components/admin/neighborhood/Edit.jsx
  src/components/admin/shop/workingHour/WorkingHour.jsx
  src/pages/AdminHome.jsx
  src/pages/customer/MonthlyReport.jsx
  src/pages/customer/visitAnalysis/DailyVisit.jsx
  src/pages/customer/visitAnalysis/DemographicVisit.jsx
  src/pages/neighborhood/WritePost.jsx
Labels: fix

#266 [Feat/#237]: 회원가입 서비스 이용약관
  src/assets/data/consentData.js
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/shop/ImageBlock.jsx
  src/components/join/CheckList.jsx
  src/components/join/CheckPopUp.jsx
  src/pages/join/Congratulate.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
Labels: feat

#275 [Feat/#267]: 랜딩페이지 레이아웃
  src/assets/data/landingData.js
  src/assets/icon/AndroidData.svg
  src/components/home/LandingCopy.jsx
  src/pages/Home.jsx
Labels: feat

#276 [Feat/#271]: 수정완료 팝업
  src/api/axios.js
  src/components/admin/formPopUp/Step4 2.jsx
  src/components/common/popUp/OneBtnPopUp.jsx
  src/components/common/popUp/TwoBtnPopUp.jsx
  src/pages/MyPage.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/BasicInfo.jsx
  src/pages/shop/StoreInfo.jsx
Labels: feat

#277 [Style/#273]: 배너 스타일 수정
  src/components/common/AdminHeader.jsx
  src/components/common/Header.jsx
  src/components/home/Banner.jsx
Labels: style

#279 [Style/#278]: 어드민 홈화면 반응형
  src/components/admin/formPopUp/FormPopUp.jsx
  src/components/admin/home/CouponInfo.jsx
  src/components/admin/home/CustomerInfo.jsx
  src/components/admin/home/DayGraphInfo.jsx
  src/components/admin/home/GenderGraphInfo.jsx
  src/components/admin/home/StoreInfo.jsx
  src/components/admin/home/WorkingHours.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/login/LoginBox.jsx
  src/pages/AdminHome.jsx
  src/pages/MyPage.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/shop/StoreInfo.jsx
Labels: style

#281 [Fix/#280]: 홈화면 서버 오류 수정
  src/App.js
  src/api/axios.js
  src/components/admin/customer/monthlyReport/AgeStatic.jsx
  src/components/admin/customer/monthlyReport/DayVisitStatic.jsx
  src/components/admin/home/DayGraphInfo.jsx
  src/components/admin/home/GenderGraphInfo.jsx
  src/components/login/LoginBox.jsx
  src/pages/AdminHome.jsx
  src/pages/customer/MonthlyReport.jsx
  src/pages/customer/visitAnalysis/DailyVisit.jsx
  src/pages/customer/visitAnalysis/DemographicVisit.jsx
  src/pages/customer/visitAnalysis/TimeVisit.jsx
  src/redux/thunks/getCustomers.js
  src/redux/thunks/getStoreInfo.js
  src/redux/thunks/modifyStoreInfo.js
Labels: fix

#283 [Style/#282]: Footer 생성
  src/assets/icon/FooterLogo.svg
  src/assets/index.js
  src/components/home/Footer.jsx
  src/components/join/CheckList.jsx
  src/pages/Home.jsx
  src/pages/join/Congratulate.jsx
  src/pages/term/PersonalInfoTerm.jsx
  src/pages/term/ServiceTerm.jsx
Labels: style

#284 [Feat/#268]: 전화번호 유효성 검사
  src/components/admin/formPopUp/FormPopUp.jsx
  src/components/admin/formPopUp/Step1.jsx
  src/pages/MyPage.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/join/JoinTwoStep.jsx
  src/pages/shop/BasicInfo.jsx
Labels: feat

#285 [Fix/#274]: 동네소식 수정 이미지, 내용
  src/components/admin/neighborhood/Edit.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/PostList.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/shop/StoreInfo.jsx
Labels: fix

#287 [Fix/#286]: 최초 팝업 오류 수정
  src/App.js
  src/components/admin/formPopUp/FormPopUp.jsx
  src/components/admin/formPopUp/Step1.jsx
  src/components/admin/home/GenderGraphInfo.jsx
  src/components/login/LoginBox.jsx
  src/pages/AdminHome.jsx
  src/pages/MyPage.jsx
  src/pages/shop/StoreInfo.jsx
Labels: fix

#292 [Style/#290]: 최초 로그인 팝업 반응형
  src/components/admin/formPopUp/FormPopUp.jsx
  src/components/admin/formPopUp/Step3.jsx
  src/components/admin/home/CouponInfo.jsx
  src/components/admin/shop/MenuItem.jsx
  src/components/common/Button.jsx
  src/components/join/CheckList.jsx
  src/components/join/CheckPopUp.jsx
  src/pages/AdminHome.jsx
  src/pages/shop/BasicInfo.jsx
Labels: style

#296 [Feat]: 신청 내역 데이터 변경
  src/components/admin/neighborhood/Edit.jsx
  src/pages/myPage/UIServiceDetail.jsx
Labels: fix, feat
