Repository UMC-5th-Coumo/Coumo_Web, pull requests merged in 2024-01, with the labels that each got.

#2 [Setting/#1] 폰트 설정
  .eslintrc.json
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/App.js
  src/assets/font/Font.css
  src/assets/font/GmarketSans/GmarketSansBold.otf
  src/assets/font/GmarketSans/GmarketSansLight.otf
  src/assets/font/GmarketSans/GmarketSansMedium.otf
  src/assets/font/woff/Pretendard-Black.woff
  src/assets/font/woff/Pretendard-Bold.woff
  src/assets/font/woff/Pretendard-ExtraBold.woff
  src/assets/font/woff/Pretendard-ExtraLight.woff
  src/assets/font/woff/Pretendard-Light.woff
  src/assets/font/woff/Pretendard-Medium.woff
  src/assets/font/woff/Pretendard-Regular.woff
  src/assets/font/woff/Pretendard-SemiBold.woff
  src/assets/font/woff/Pretendard-Thin.woff
  src/assets/font/woff2/Pretendard-Black.woff2
  src/assets/font/woff2/Pretendard-Bold.woff2
  src/assets/font/woff2/Pretendard-ExtraBold.woff2
  src/assets/font/woff2/Pretendard-ExtraLight.woff2
  src/assets/font/woff2/Pretendard-Light.woff2
  src/assets/font/woff2/Pretendard-Medium.woff2
  src/assets/font/woff2/Pretendard-Regular.woff2
  src/assets/font/woff2/Pretendard-SemiBold.woff2
  src/assets/font/woff2/Pretendard-Thin.woff2
  src/styled/GlobalStyle.js
Labels: setting

#4 [Setting/#3] 폰트 설정 수정, 컬러 변수 정의
  .prettierrc
  package-lock.json
  package.json
  src/App.js
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: setting

#9 [Feat/#5]: Header 컴포넌트, pages 추가 (수정)
  package-lock.json
  package.json
  src/App.js
  src/assets/icon/Logo.svg
  src/assets/index.js
  src/components/common/Header.jsx
  src/index.js
  src/pages/Coupon.jsx
  src/pages/Customer.jsx
  src/pages/Home.jsx
  src/pages/Neighborhood.jsx
  src/pages/Shop.jsx
Labels: feat

#15 [Feat/#13]: 게시글 컴포넌트
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/TagButton.jsx
  src/pages/Neighborhood.jsx
Labels: feat

#16 [Feat/#8]: 공통 컴포넌트 생성
  src/assets/data/basicInfoTabs.js
  src/assets/data/storeData.js
  src/assets/data/writingTabs.js
  src/components/common/Button.jsx
  src/components/common/Header.jsx
  src/components/common/Input.jsx
  src/components/common/RadioBtn.jsx
  src/components/common/Tab.jsx
  src/components/common/TabBar.jsx
  src/pages/Shop.jsx
  src/styles/theme.js
Labels: feat

#18 [Feat/#14]: 동네소식 - 내가 쓴 글 보기 페이지
  src/assets/icon/line.svg
  src/assets/index.js
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/TagButton.jsx
  src/components/common/Button.jsx
  src/components/common/Header.jsx
  src/components/common/TabBar.jsx
  src/components/common/Title.jsx
  src/pages/Neighborhood.jsx
  src/pages/neighborhood/MyPosts.jsx
Labels: feat

#21 [Feat/#17]: 로그인 박스, 로그인 페이지
  src/App.js
  src/assets/icon/LoginBackground.svg
  src/assets/icon/LoginId.svg
  src/assets/icon/LoginPw.svg
  src/assets/icon/LoginSave.svg
  src/assets/icon/LoginSaveCheck.svg
  src/assets/index.js
  src/components/common/Button.jsx
  src/components/common/Header.jsx
  src/components/login/LoginBox.jsx
  src/pages/Login.jsx
  src/styles/GlobalStyle.js
Labels: feat

#24 [Fix]: 헤더 오류 수정
  src/components/common/Button.jsx
  src/styles/GlobalStyle.js
Labels: fix

#26 [Feat/#22]: 매장관리 - 기본 정보 페이지
  src/components/common/Button.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/shop/BasicInfo.jsx
Labels: feat

#27 [Feat/#25]: 동네 소식 - 글쓰기
  package-lock.json
  package.json
  src/assets/data/writecategoryData.js
  src/components/admin/coupon/Category.jsx
  src/components/common/FormPopUp.jsx
  src/components/common/Input.jsx
  src/components/common/RadioBtn.jsx
  src/components/writePost/Edit.jsx
  src/pages/Neighborhood.jsx
  src/pages/Shop.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/BasicInfo.jsx
Labels: feat

#32 [Feat/#31] 고객 데이터 관리 공통 컴포넌트
  src/assets/data/tabData.js
  src/components/admin/customer/CustomerCard.jsx
  src/components/admin/customer/groupTab/GroupTab.jsx
  src/components/admin/customer/groupTab/GroupTabBar.jsx
  src/components/admin/customer/index/Index.jsx
  src/components/admin/customer/index/IndexBar.jsx
  src/components/admin/customer/tabMenu/TabMenu.jsx
  src/components/admin/customer/tabMenu/TabMenuBar.jsx
  src/pages/Customer.jsx
  src/styles/theme.js
Labels: feat

#37 [Feat/#36] 쿠폰 등록 페이지
  package-lock.json
  package.json
  src/assets/data/stampData.js
  src/assets/icon/stampExample.png
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/coupon/RadioButton.jsx
  src/components/admin/coupon/Stamp.jsx
  src/components/admin/coupon/StampCount.jsx
  src/components/admin/coupon/StampList.jsx
  src/components/admin/customer/MonthPicker.jsx
  src/components/common/Title.jsx
  src/pages/coupon/AddCoupon.jsx
Labels: feat

#38 [Feat/#30] 동네 소식 - 내가 쓴 글 수정하기
  src/App.js
  src/components/admin/neighborhood/Post.jsx
  src/components/common/Header.jsx
  src/components/common/Tab.jsx
  src/components/common/TabBar.jsx
  src/components/writePost/Edit.jsx
  src/pages/Coupon.jsx
  src/pages/Neighborhood.jsx
  src/pages/Shop.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/styles/theme.js
Labels: feat

#41 [Style/#40] 전체적인 사이즈 수정
  src/assets/data/priceData.js
  src/assets/icon/LoginId.svg
  src/assets/icon/LoginPw.svg
  src/assets/icon/Logo.svg
  src/assets/icon/arrow.svg
  src/components/admin/coupon/Category.jsx
  src/components/admin/coupon/ColorPicker.jsx
  src/components/admin/coupon/RadioButton.jsx
  src/components/admin/coupon/Stamp.jsx
  src/components/admin/customer/Calendar.jsx
  src/components/admin/customer/MonthPicker.jsx
  src/components/admin/customer/groupTab/GroupTab.jsx
  src/components/admin/customer/index/Index.jsx
  src/components/admin/customer/index/IndexBar.jsx
  src/components/admin/customer/tabMenu/TabMenu.jsx
  src/components/admin/customer/tabMenu/TabMenuBar.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/neighborhood/TagButton.jsx
  src/components/common/Button.jsx
  src/components/common/FormPopUp.jsx
  src/components/common/Header.jsx
  src/components/common/Input.jsx
  src/components/common/RadioBtn.jsx
  src/components/common/Tab.jsx
  src/components/common/Title.jsx
  src/components/home/Banner.jsx
  src/components/home/Plan.jsx
  src/components/home/PricePlan.jsx
  src/components/login/LoginBox.jsx
  src/components/writePost/Edit.jsx
  src/pages/Login.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/shop/BasicInfo.jsx
  src/styles/GlobalStyle.js
Labels: style

#44 [Feat/#35]: 회원가입 페이지
  package-lock.json
  package.json
  src/App.js
  src/assets/icon/CheckBoxDefault.svg
  src/assets/icon/CheckBoxSelected.svg
  src/assets/icon/LogoCongratulate.svg
  src/assets/index.js
  src/components/common/Input.jsx
  src/components/common/InputJoin.jsx
  src/components/login/LoginBox.jsx
  src/components/writePost/Edit.jsx
  src/pages/FindId.jsx
  src/pages/FindPw.jsx
  src/pages/join/Congratulate.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/shop/BasicInfo.jsx
Labels: feat

#46 [Feat/#45]: 쿠폰 UI 구매 서비스 소개 페이지
  src/assets/data/couponStepData.js
  src/assets/data/reasonData.js
  src/assets/icon/CouponPeach.svg
  src/assets/icon/CouponYellow.svg
  src/assets/icon/UIArticle.svg
  src/assets/index.js
  src/components/admin/coupon/CouponStep.jsx
  src/components/admin/coupon/ReasonCard.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/common/Tab.jsx
  src/components/common/TabBar.jsx
  src/pages/Coupon.jsx
  src/pages/Neighborhood.jsx
  src/pages/Shop.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/coupon/UIServiceAd.jsx
  src/pages/coupon/UIServiceForm.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/BasicInfo.jsx
  src/styles/theme.js
Labels: feat

#49 [fix/#48]: 쿠폰관리 페이지 일부 수정
  src/components/admin/coupon/Stamp.jsx
  src/components/admin/coupon/StampList.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/coupon/UIServiceAd.jsx
  src/pages/coupon/UIServiceForm.jsx
Labels: fix

#51 [Feat/#50]: 고객 데이터 방문자수 컴포넌트
  src/assets/icon/arrow-down.svg
  src/assets/icon/arrow-up.svg
  src/assets/index.js
  src/components/admin/customer/VisitCount.jsx
  src/components/admin/customer/charts/BarChart.jsx
  src/components/admin/customer/charts/DoughnutChart.jsx
  src/components/common/Header.jsx
  src/pages/customer/visitAnalysis/DailyVisit.jsx
  src/pages/customer/visitAnalysis/DemographicVisit.jsx
  src/pages/customer/visitAnalysis/TimeVisit.jsx
Labels: feat

#52 [Feat/#47] 매장설명 탭
  src/assets/icon/Plus.svg
  src/assets/icon/SmallPlus.svg
  src/assets/index.js
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/MenuMore.jsx
  src/components/admin/writePost/Edit.jsx
  src/components/common/TabBar.jsx
  src/pages/coupon/AddCoupon.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPostView.jsx
  src/pages/neighborhood/MyPosts.jsx
  src/pages/neighborhood/WritePost.jsx
  src/pages/shop/BasicInfo.jsx
  src/pages/shop/StoreInfo.jsx
  src/styles/theme.js
Labels: feat

#54 [API/#53]: axios instance 생성
  src/api/axios.js
Labels: API

#57 [Fix/#56] 이미지 삽입 코드 수정, 삭제 경고창 추가
  src/components/admin/neighborhood/ConfirmModal.jsx
  src/components/admin/neighborhood/Post.jsx
  src/components/admin/shop/ImageBlock.jsx
  src/components/admin/shop/MenuMore.jsx
  src/pages/neighborhood/MyEdit.jsx
  src/pages/neighborhood/MyPosts.jsx
Labels: fix

#58 [Feat/#55]: 고객 데이터 관리 페이지
  src/assets/icon/calendar.svg
  src/assets/icon/line_long.svg
  src/assets/image/userImage.png
  src/assets/index.js
  src/components/admin/customer/common/charts/BarChart.jsx
  src/components/admin/customer/common/charts/DoughnutChart.jsx
  src/components/admin/customer/common/charts/LineChart.jsx
  src/components/admin/customer/common/tabMenu/TabMenu.jsx
  src/components/admin/customer/common/tabMenu/TabMenuBar.jsx
  src/components/admin/customer/customerManage/CustomerCard.jsx
  src/components/admin/customer/customerManage/CustomerDetail.jsx
  src/components/admin/customer/customerManage/CustomerGroupButton.jsx
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/components/admin/customer/customerManage/RangeCalendar.jsx
  src/components/admin/customer/monthlyReport/MonthPicker.jsx
  src/components/admin/customer/visitAnalysis/Calendar.jsx
  src/components/admin/customer/visitAnalysis/VisitCount.jsx
  src/components/admin/customer/visitAnalysis/groupTab/GroupTab.jsx
  src/components/admin/customer/visitAnalysis/groupTab/GroupTabBar.jsx
  src/components/admin/customer/visitAnalysis/index/Index.jsx
  src/components/admin/customer/visitAnalysis/index/IndexBar.jsx
  src/components/common/RadioBtn.jsx
  src/pages/Customer.jsx
  src/pages/customer/CustomerManage.jsx
  src/pages/customer/MonthlyReport.jsx
  src/pages/customer/VisitAnalysis.jsx
  src/pages/customer/visitAnalysis/DailyVisit.jsx
  src/pages/customer/visitAnalysis/DemographicVisit.jsx
  src/pages/customer/visitAnalysis/TimeVisit.jsx
  src/styles/index.css
Labels: feat

#60 [Feat/#59]: 마이페이지
  src/App.js
  src/assets/icon/call.svg
  src/assets/icon/detail-arrow.svg
  src/assets/index.js
  src/components/common/Title.jsx
  src/pages/MyPage.jsx
  src/pages/coupon/UIServiceForm.jsx
Labels: feat

#62 [Setting/#61]: redux-toolkit 초기 세팅
  package-lock.json
  package.json
  src/index.js
  src/redux/reducer.js
  src/redux/store.js
Labels: setting

#64 [Style/#63]: 쿠폰 도장 개수 수정
  src/components/admin/coupon/StampCount.jsx
  src/pages/coupon/AddCoupon.jsx
Labels: style

#66 [Fix/#65]: 고객 관리 > 방문기간, 아이디 제거
  src/components/admin/customer/customerManage/CustomerCard.jsx
  src/components/admin/customer/customerManage/RangeCalendar.jsx
  src/pages/customer/CustomerManage.jsx
Labels: fix

#70 [Fix/#69] 회원가입 > 주소 제거, 매장관리> 상세주소 추가
  src/pages/join/JoinTwoStep.jsx
  src/pages/shop/BasicInfo.jsx
Labels: fix

#71 [Redux/#67]: 유저 데이터 redux 연동
  .eslintrc.json
  package-lock.json
  package.json
  src/components/login/LoginBox.jsx
  src/index.js
  src/redux/reducer.js
  src/redux/slices/userSlice.js
  src/redux/store.js
Labels: redux

#75 [Feat/#74]: 쿠폰 등록 > 폰트 색상 변경 기능 추가
  src/components/admin/coupon/ColorPicker.jsx
  src/pages/coupon/AddCoupon.jsx
Labels: feat

#77 [Redux/#76]: 고객 데이터 redux 연동
  src/components/admin/customer/customerManage/CustomerList.jsx
  src/pages/customer/CustomerManage.jsx
  src/redux/reducer.js
  src/redux/slices/customerSlice.js
  src/redux/store.js
  src/redux/thunks/getCustomers.js
Labels: redux

#80 [Feat/#68] 아이디, 비밀번호 찾기 페이지
  src/components/common/FindForm.jsx
  src/components/common/InputJoin.jsx
  src/components/login/LoginBox.jsx
  src/pages/FindId.jsx
  src/pages/FindPw.jsx
  src/pages/join/JoinOneStep.jsx
  src/pages/join/JoinTwoStep.jsx
Labels: feat

#82 [Style/#79]: 헤더, 랜딩 페이지 반응형 구현
  src/components/common/Header.jsx
  src/components/home/Banner.jsx
  src/components/home/Plan.jsx
  src/components/home/PricePlan.jsx
Labels: style
